import { StyleProp, TextStyle, ViewStyle } from 'react-native';

export type I_ThemeModes = 'light' | 'dark';

// Definition of all colors/values
// available for theming
export interface I_ThemeDefinitionScss {
  background?: string;
  background_contrast?: string;
  background_contrast_2?: string;
  background_gradient?: string;
  background_high?: string;
  background_low?: string;
  border?: string;
  border_contrast?: string;
  border_radius?: string;
  button_background?: string;
  button_border?: string;
  button_danger_alt_background?: string;
  button_danger_alt_border?: string;
  button_danger_alt_icon?: string;
  button_danger_alt_interactive_background?: string;
  button_danger_alt_interactive_border?: string;
  button_danger_alt_interactive_icon?: string;
  button_danger_alt_interactive_text?: string;
  button_danger_alt_text?: string;
  button_danger_background?: string;
  button_danger_border?: string;
  button_danger_icon?: string;
  button_danger_interactive_background?: string;
  button_danger_interactive_border?: string;
  button_danger_interactive_icon?: string;
  button_danger_interactive_text?: string;
  button_danger_text?: string;
  button_ghost_background?: string;
  button_ghost_icon?: string;
  button_ghost_interactive_background?: string;
  button_ghost_interactive_icon?: string;
  button_ghost_interactive_text?: string;
  button_ghost_text?: string;
  button_icon?: string;
  button_interactive_background?: string;
  button_interactive_border?: string;
  button_interactive_icon?: string;
  button_interactive_text?: string;
  button_primary_background?: string;
  button_primary_border?: string;
  button_primary_icon?: string;
  button_primary_interactive_background?: string;
  button_primary_interactive_border?: string;
  button_primary_interactive_icon?: string;
  button_primary_interactive_text?: string;
  button_primary_text?: string;
  button_secondary_background?: string;
  button_secondary_border?: string;
  button_secondary_icon?: string;
  button_secondary_interactive_background?: string;
  button_secondary_interactive_border?: string;
  button_secondary_interactive_icon?: string;
  button_secondary_interactive_text?: string;
  button_secondary_text?: string;
  button_text?: string;
  color_blue?: string;
  color_blue_interactive?: string;
  color_blue_tint_1?: string;
  color_blue_tint_2?: string;
  color_danger?: string;
  color_danger_interactive?: string;
  color_danger_tint_1?: string;
  color_danger_tint_2?: string;
  color_green?: string;
  color_green_interactive?: string;
  color_green_tint_1?: string;
  color_green_tint_2?: string;
  color_indigo?: string;
  color_indigo_interactive?: string;
  color_indigo_tint_1?: string;
  color_indigo_tint_2?: string;
  color_lime?: string;
  color_lime_interactive?: string;
  color_lime_tint_1?: string;
  color_lime_tint_2?: string;
  color_neutral?: string;
  color_neutral_interactive?: string;
  color_neutral_tint_1?: string;
  color_neutral_tint_2?: string;
  color_orange?: string;
  color_orange_interactive?: string;
  color_orange_tint_1?: string;
  color_orange_tint_2?: string;
  color_pink?: string;
  color_pink_interactive?: string;
  color_pink_tint_1?: string;
  color_pink_tint_2?: string;
  color_primary?: string;
  color_primary_interactive?: string;
  color_primary_tint_1?: string;
  color_primary_tint_2?: string;
  color_purple?: string;
  color_purple_interactive?: string;
  color_purple_tint_1?: string;
  color_purple_tint_2?: string;
  color_red?: string;
  color_red_interactive?: string;
  color_red_tint_1?: string;
  color_red_tint_2?: string;
  color_success?: string;
  color_success_interactive?: string;
  color_success_tint_1?: string;
  color_success_tint_2?: string;
  color_teal?: string;
  color_teal_interactive?: string;
  color_teal_tint_1?: string;
  color_teal_tint_2?: string;
  color_warning?: string;
  color_warning_interactive?: string;
  color_warning_tint_1?: string;
  color_warning_tint_2?: string;
  color_yellow?: string;
  color_yellow_interactive?: string;
  color_yellow_tint_1?: string;
  color_yellow_tint_2?: string;
  control_background?: string;
  control_border?: string;
  control_disabled_background?: string;
  control_disabled_border?: string;
  control_disabled_icon?: string;
  control_disabled_placeholder?: string;
  control_disabled_text?: string;
  control_error_background?: string;
  control_error_border?: string;
  control_error_icon?: string;
  control_error_text?: string;
  control_focus_background?: string;
  control_focus_border?: string;
  control_hover_background?: string;
  control_hover_border?: string;
  control_icon?: string;
  control_placeholder?: string;
  control_text?: string;
  disabled_opacity?: string;
  focus_highlight?: string;
  focus_shadow?: string;
  icon?: string;
  icon_dark?: string;
  icon_light?: string;
  icon_muted?: string;
  text?: string;
  text_contrast?: string;
  text_contrast_muted?: string;
  text_highlighted?: string;
  text_highlighted_background?: string;
  text_muted?: string;
}

// colors module contains a variable called "themes"
// and the rest of pairs key-value are extracted from
// themes in the form of "sds_theme_dark_key: value"
export interface I_ColorsScss {
  themes: string;
  themes2: boolean;
  [key: string]: StyleProp<ViewStyle> | StyleProp<TextStyle> | string;
  'sds-light-example': StyleProp<ViewStyle>;
  'sds-dark-example': StyleProp<ViewStyle>;
  'sds-my-own-example': StyleProp<ViewStyle>;
}

export const colors: I_ColorsScss;

export default colors;
